name: 'Simulator to Get Secrets'

description: 'GitHub action for retrieving secrets'

inputs:
  secret-ids:
    description: 'One or more secret names or secret prefixes to retrieve'
    required: true

runs:
  using: "composite"
  steps:
    - name: Print Inputs
      run: |
        echo ${{ inputs.secret-ids }}
      shell: bash